#!/bin/bash

# Bash file allowing to update the Slicer's SVN & SlicerDocker's SVN automatically

script_dir="`cd $(dirname $0); pwd`"

echo "*********************************************"
echo "*************** Slicer UPDATE ***************"
echo "*********************************************"

pushd $HOME/MyProjects/Slicer/

current_slicer_branch="`git branch | grep \* | cut -d ' ' -f2`"

# unique timestamp
slicer_t=timestamp-$(date +%s)

# stash with message
slicer_r=$(git stash save $slicer_t)
echo $slicer_r

# check if the value exists
slicer_v=$(echo $slicer_r|grep $slicer_t)

#update master and its svn
git checkout master
git fetch origin
git rebase origin/master
git svn rebase


echo "*********************************************"
echo "************ SlicerDocker UPDATE ************"
echo "*********************************************"

pushd $HOME/MyProjects/Docker/SlicerDocker/

current_slicerdocker_branch="`git branch | grep \* | cut -d ' ' -f2`"

# unique timestamp
slicerdocker_t=timestamp-$(date +%s)

# stash with message
slicerdocker_r=$(git stash save $slicerdocker_t)
echo $slicerdocker_r

# check if the value exists
slicerdocker_v=$(echo $slicerdocker_r|grep $slicerdocker_t)

#update master and its svn
git checkout master
git fetch origin
git rebase origin/master
git checkout -b update-$(date +%F)
git config --global svn.rmdir true
./slicer-base/update.sh $HOME/MyProjects/Slicer
git push MayeulChassagnard/SlicerDocker update-$(date +%F)

git checkout $current_slicerdocker_branch

#remove tmp branch pushed to update svn
git branch -D update-$(date +%F)

# if smthing stashed
if [ "$slicerdocker_v" ]; then
  git stash pop
else
  echo "Nothing stashed"
fi

popd


# Back to Slicer

git checkout $current_slicer_branch

# if smthing stashed
if [ "$slicer_v" ]; then
  git stash pop
else
  echo "Nothing stashed"
fi

popd

